name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start Jpb"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Npm Install and Build
        run: |
          npm install
          npm run build
      - name: Check Result
        run: |
          ls ${{ github.workspace }}
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          EXCLUDE: "/dist/, /node_modules/"
      - run: echo "🍏 This job's status is ${{ job.status }}."
